### ISSUE TITLE
Trying to run helloworld program...

### ISSUE THREAD

**Issue by datamaskinen** [thiagoralves/OpenPLC_Editor#27]
Beremiz_service:  1.0
Traceback (most recent call last):
Release: 2021-02-22
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 221, in <module>
    class ParamsEntryDialog(wx.TextEntryDialog):
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 223, in ParamsEntryDialog
    def __init__(self, parent, message, caption=_("Please enter text"), defaultValue="",
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 189, in unicode_translation
    return wx.GetTranslation(message).encode(default_locale)
TypeError: encode() argument 1 must be string, not None
"/usr/bin/python2.7" "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py" -p 61546 -i localhost -x 1 /tmp/tmpDa09xe
exited with status 1 (pid 50110)
PYRO connecting to URI : PYROLOC://127.0.0.1:61546
Exception while connecting to 'LOCAL://': connection failed
Connection failed to LOCAL://!

**Comment by datamaskinen** [comment]
this is from running it strait in terminal..... 

/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py -p 61605 -i localhost -x 1 /tmp/tmpjCfYaP
/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py:345: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  dlg.SetTests([(lambda name: len(name) is not 0, _("Name must not be null!"))])
Traceback (most recent call last):
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 35, in <module>
    from past.builtins import execfile
ModuleNotFoundError: No module named 'past'
(focal_amd64)root@littleflapper:~# /home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py:345: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  dlg.SetTests([(lambda name: len(name) is not 0, _("Name must not be null!"))])
Traceback (most recent call last):
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 35, in <module>
    from past.builtins import execfile
ModuleNotFoundError: No module named 'past'
(focal_amd64)root@littleflapper:~# /home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py -p 61605 -i localhost -x 1 /tmp/tmpjCfYaP
/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py:345: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  dlg.SetTests([(lambda name: len(name) is not 0, _("Name must not be null!"))])
Traceback (most recent call last):
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 35, in <module>
    from past.builtins import execfile
ModuleNotFoundError: No module named 'past'

**Comment by datamaskinen** [comment]
that first was when using python 3....

Now using python2.7 i get this:

(focal_amd64)root@littleflapper:~# /home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py -p 61605 -i localhost -x 1 /tmp/tmpjCfYaP
Traceback (most recent call last):
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 144, in <module>
    os.chdir(WorkingDir)
OSError: [Errno 2] No such file or directory: '/tmp/tmpjCfYaP'
(focal_amd64)root@littleflapper:~# /home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py -p 61605 -i localhost -x 1 /tmp/tmpjCfYaP
Traceback (most recent call last):
  File "/home/marlin/opt/OpenPLC_Editor/editor/Beremiz_service.py", line 144, in <module>
    os.chdir(WorkingDir)
OSError: [Errno 2] No such file or directory: '/tmp/tmpjCfYaP'

**Comment by datamaskinen** [comment]
it might be me missing some librarys or something as i installed it in a chroot ....

**Comment by datamaskinen** [comment]
the editor works as it should and all ... it is just when  i try to simulate a run it gives me an error....

**Comment by datamaskinen** [comment]
hehe this was the solution  "export LANG=en_US.utf-8"
