### ISSUE TITLE
Missing _convert_agg_to_wx_bitmap in dev-python3

### ISSUE THREAD

**Issue by petrkr** [thiagoralves/OpenPLC_Editor#62]
Since python2 is deprecated already for 3 years, it is not longer available in most of modern systems.. Thus I trying dev-python3 branch, but it seems to using some deprecated libraries too.

It can not start up, because it tries to import private (!!) function from matplotlib (_convert_agg_to_wx_bitmap). I do not know in which exact version they removed this private function, but in 3.6.2 it's already not available. By google I can see some archived docs for version 3.0.0 (https://matplotlib.org/3.0.0/_modules/matplotlib/backends/backend_wxagg.html) where this function is still present.

Because I do not know what it should do, I can not provide proper FIX and PR for it :(

```
Traceback (most recent call last):
  File "/home/petrkr/svn/OpenPLC_Editor/editor/Beremiz.py", line 204, in AppStart
    self.BackgroundInitialization()
  File "/home/petrkr/svn/OpenPLC_Editor/editor/Beremiz.py", line 137, in BackgroundInitialization
    self.ImportModules()
  File "/home/petrkr/svn/OpenPLC_Editor/editor/Beremiz.py", line 180, in ImportModules
    mod = __import__(modname)
  File "/home/petrkr/svn/OpenPLC_Editor/editor/BeremizIDE.py", line 42, in <module>
    from editors.EditorPanel import EditorPanel
  File "/home/petrkr/svn/OpenPLC_Editor/editor/editors/EditorPanel.py", line 29, in <module>
    from controls import VariablePanel
  File "/home/petrkr/svn/OpenPLC_Editor/editor/controls/__init__.py", line 34, in <module>
    from controls.DebugVariablePanel import DebugVariablePanel
  File "/home/petrkr/svn/OpenPLC_Editor/editor/controls/DebugVariablePanel/__init__.py", line 26, in <module>
    from controls.DebugVariablePanel.DebugVariablePanel import DebugVariablePanel
  File "/home/petrkr/svn/OpenPLC_Editor/editor/controls/DebugVariablePanel/DebugVariablePanel.py", line 44, in <module>
    from controls.DebugVariablePanel.DebugVariableTextViewer import DebugVariableTextViewer
  File "/home/petrkr/svn/OpenPLC_Editor/editor/controls/DebugVariablePanel/DebugVariableTextViewer.py", line 31, in <module>
    from controls.DebugVariablePanel.DebugVariableViewer import DebugVariableViewer
  File "/home/petrkr/svn/OpenPLC_Editor/editor/controls/DebugVariablePanel/DebugVariableViewer.py", line 32, in <module>
    from matplotlib.backends.backend_wxagg import _convert_agg_to_wx_bitmap
ImportError: cannot import name '_convert_agg_to_wx_bitmap' from 'matplotlib.backends.backend_wxagg' (/usr/lib/python3.10/site-packages/matplotlib/backends/backend_wxagg.py)
```

**Comment by petrkr** [comment]
"fixed" by #63
